### PR TITLE
Enable interval serialization

### PR DESCRIPTION
**Pull request by PetrBainar**

### CODE REVIEW

**Comment by maarzt** [comment]
The PR should be improved:

1. ```ObjectMapperModifier``` should be a interface not an abstract class.
1. Instead of ```ObjectMapperModifier``` I would like to have more meaningful interfaces like ```JsonSerializer``` and ```JsonDeserializer```. Both should have a nice easy to implement interface.
1. An example should be included like maybe serializer and deserializer for ```Interval```.
1. ```JsonService``` should become a real ```SciJavaService```.

**Comment by ctrueden** [comment]
Thanks for reviewing, @maarzt!

About the `JsonService` and other non-SciJava services: I think part of the confusion is that the Dropwizard stack has its own service model, so the term "service" becomes technically ambiguous in this project. And further adding to this confusion: I don't think the `JsonService` is a Dropwizard service either! >_<

It would be nice if someone who takes the time to understand both architectures (SciJava and Dropwizard) could clean up this project. But I don't think `JsonService` not being a SciJava service is a blocker for this PR.

**Comment by kozusznik** [comment]
I have incorporated  suggestions 1 and 2 - it is commited in this branch.

**Comment by PetrBainar** [comment]
Suggestion #4 has been addressed by creating an issue (https://github.com/imagej/imagej-server/issues/31)

**Comment by PetrBainar** [comment]
> Consider using interface type Map instead of class.
> Consider using HashMap instead of LinkedHashMap

Addressed

**Comment by PetrBainar** [comment]
I think that all suggestions have been addressed. @maarzt and @ctrueden do you guys think we can carry on and merge? Thank you!

**Pull request merged**
